[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_escrow = "HwpaZvifoU61b59fxa2Mo1YRLYuWUtn1spZ9XKs5QD5Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/victorcarvalho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
